import mymodule

mymodule.root.title("Text-to-speech conversion with translation")
mymodule.root.geometry("1000x800")
mymodule.root.iconbitmap("speaker-image.ico")     
checkbox1=mymodule.Checkbutton(mymodule.root, text="English", variable=mymodule.en_var, command=mymodule.check)
checkbox1.pack(padx=20, pady=20)
checkbox2=mymodule.Checkbutton(mymodule.root, text="French", variable=mymodule.fr_var, command=mymodule.check)
checkbox2.pack(padx=20, pady=20)
checkbox3=mymodule.Checkbutton(mymodule.root, text="Dutch", variable=mymodule.nl_var, command=mymodule.check)
checkbox3.pack(padx=20, pady=20)
checkbox4=mymodule.Checkbutton(mymodule.root, text="Spanish", variable=mymodule.es_var, command=mymodule.check)
checkbox4.pack(padx=20, pady=20)
checkbox5=mymodule.Checkbutton(mymodule.root, text="German", variable=mymodule.de_var, command=mymodule.check)
checkbox5.pack(padx=20, pady=20)
checkbox6=mymodule.Checkbutton(mymodule.root, text="Tamil", variable=mymodule.ta_var, command=mymodule.check)
checkbox6.pack(padx=20, pady=20)
convertbutton= mymodule.Button(mymodule.root, text="convert",command=mymodule.convert)
convertbutton.pack(padx=20)
view_audio_button = mymodule.Button(mymodule.root, text="View your Audio files", command=mymodule.open_audio_files)
view_audio_button.pack(padx=20, pady=20)
mymodule.root.mainloop()
print("Text-to-speech conversion with translation complete.")